In [1]:
import numpy as np

In [2]:
arr1 = np.array([[3,5,7]])

In [5]:
arr1

array([[3, 5, 7]])

In [3]:
arr2 = np.zeros(50)

In [4]:
arr2

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
arr3 = np.array([[2,4], [8,9], [7,6]])

In [7]:
arr3

array([[2, 4],
       [8, 9],
       [7, 6]])

In [10]:
arr1.T

array([[3],
       [5],
       [7]])

In [13]:
arr4 = arr1.T * arr3

In [14]:
arr4

array([[ 6, 12],
       [40, 45],
       [49, 42]])

In [15]:
arr2[4] = 5

In [16]:
arr2

array([0., 0., 0., 0., 5., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
if np.shape(arr4)==(1,2) and arr2[4]!=0:
  print("Passed")
else:
    print("Fail")

Fail


In [19]:
I = np.identity(3)

In [20]:
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
I_ = 9*I + 1

In [28]:
I_

array([[10.,  1.,  1.],
       [ 1., 10.,  1.],
       [ 1.,  1., 10.]])

In [25]:
dot_product = np.dot(I,I_)

In [26]:
dot_product

array([[10.,  1.,  1.],
       [ 1., 10.,  1.],
       [ 1.,  1., 10.]])